2020-10-20 22:55:30,078 INFO    MainThread:11756 [wandb_init.py:_log_setup():292] Logging user logs to wandb\run-20201020_225530-lbbbl9xy\logs\debug.log
2020-10-20 22:55:30,078 INFO    MainThread:11756 [wandb_init.py:_log_setup():293] Logging internal logs to wandb\run-20201020_225530-lbbbl9xy\logs\debug-internal.log
2020-10-20 22:55:30,078 INFO    MainThread:11756 [wandb_setup.py:_flush():69] setting env: {}
2020-10-20 22:55:30,078 INFO    MainThread:11756 [wandb_setup.py:_flush():69] setting user settings: {'email': 'delimited@live.com'}
2020-10-20 22:55:30,078 INFO    MainThread:11756 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn
2020-10-20 22:55:33,011 INFO    MainThread:11756 [wandb_run.py:_console_start():1276] atexit reg
2020-10-20 22:55:33,023 INFO    MainThread:11756 [wandb_run.py:_redirect():1146] redirect: SettingsConsole.WRAP
2020-10-20 22:55:33,023 INFO    MainThread:11756 [wandb_run.py:_redirect():1177] Wrapping output streams.
2020-10-20 22:55:33,023 INFO    MainThread:11756 [wandb_run.py:_redirect():1193] Redirects installed.
2020-10-20 22:55:33,033 INFO    MainThread:11756 [wandb_run.py:_atexit_cleanup():1249] got exitcode: 1
2020-10-20 22:55:33,033 INFO    MainThread:11756 [wandb_run.py:_restore():1221] restore
2020-10-20 22:55:33,377 INFO    MainThread:11756 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "d1be208fdec241caba03a5ec64a0c8a4"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 758
    }
  }
}

2020-10-20 22:55:35,388 INFO    MainThread:11756 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "928b2147255e4d52b27d81d7cb56c366"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7210
      total_bytes: 7210
    }
  }
}

2020-10-20 22:55:36,556 INFO    MainThread:11756 [wandb_run.py:_show_files():1554] logging synced files
2020-10-20 22:55:36,562 INFO    MainThread:11756 [internal.py:handle_exit():137] Internal process exited
