2020-10-20 22:05:05,711 INFO    MainThread:10540 [wandb_init.py:_log_setup():292] Logging user logs to wandb\run-20201020_220505-1toezvre\logs\debug.log
2020-10-20 22:05:05,711 INFO    MainThread:10540 [wandb_init.py:_log_setup():293] Logging internal logs to wandb\run-20201020_220505-1toezvre\logs\debug-internal.log
2020-10-20 22:05:05,711 INFO    MainThread:10540 [wandb_setup.py:_flush():69] setting env: {}
2020-10-20 22:05:05,711 INFO    MainThread:10540 [wandb_setup.py:_flush():69] setting user settings: {'email': 'delimited@live.com'}
2020-10-20 22:05:05,711 INFO    MainThread:10540 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn
2020-10-20 22:05:08,457 INFO    MainThread:10540 [wandb_run.py:_console_start():1276] atexit reg
2020-10-20 22:05:08,464 INFO    MainThread:10540 [wandb_run.py:_redirect():1146] redirect: SettingsConsole.WRAP
2020-10-20 22:05:08,465 INFO    MainThread:10540 [wandb_run.py:_redirect():1177] Wrapping output streams.
2020-10-20 22:05:08,465 INFO    MainThread:10540 [wandb_run.py:_redirect():1193] Redirects installed.
2020-10-20 22:05:08,869 INFO    MainThread:10540 [wandb_run.py:_atexit_cleanup():1249] got exitcode: 1
2020-10-20 22:05:08,870 INFO    MainThread:10540 [wandb_run.py:_restore():1221] restore
2020-10-20 22:05:08,879 INFO    MainThread:10540 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "a61c5b85a73243edac55bb4199638f42"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 756
      total_bytes: 756
    }
  }
}

2020-10-20 22:05:10,890 INFO    MainThread:10540 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "6f68d21bc83b48fa856355415a171922"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 10414
      total_bytes: 10414
    }
  }
}

2020-10-20 22:05:12,023 INFO    MainThread:10540 [wandb_run.py:_show_files():1554] logging synced files
2020-10-20 22:05:12,030 INFO    MainThread:10540 [internal.py:handle_exit():137] Internal process exited
