Traceback (most recent call last):
  File "c:/Users/delim/Desktop/AI in A&F Indiv Assignment/Practical Assessment/Prediction/gradient_boosting.py", line 12, in <module>
    data = pd.read_csv('listings_clean.csv')
  File "C:\Users\delim\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\delim\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\delim\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\delim\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\delim\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File listings_clean.csv does not exist: 'listings_clean.csv'
