2020-10-20 23:04:32,771 INFO    MainThread:10196 [wandb_init.py:_log_setup():292] Logging user logs to wandb\run-20201020_230432-1tsypuz4\logs\debug.log
2020-10-20 23:04:32,771 INFO    MainThread:10196 [wandb_init.py:_log_setup():293] Logging internal logs to wandb\run-20201020_230432-1tsypuz4\logs\debug-internal.log
2020-10-20 23:04:32,771 INFO    MainThread:10196 [wandb_setup.py:_flush():69] setting env: {}
2020-10-20 23:04:32,771 INFO    MainThread:10196 [wandb_setup.py:_flush():69] setting user settings: {'email': 'delimited@live.com'}
2020-10-20 23:04:32,771 INFO    MainThread:10196 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn
2020-10-20 23:04:35,282 INFO    MainThread:10196 [wandb_run.py:_console_start():1276] atexit reg
2020-10-20 23:04:35,295 INFO    MainThread:10196 [wandb_run.py:_redirect():1146] redirect: SettingsConsole.WRAP
2020-10-20 23:04:35,295 INFO    MainThread:10196 [wandb_run.py:_redirect():1177] Wrapping output streams.
2020-10-20 23:04:35,296 INFO    MainThread:10196 [wandb_run.py:_redirect():1193] Redirects installed.
2020-10-20 23:04:35,342 INFO    MainThread:10196 [wandb_run.py:_atexit_cleanup():1249] got exitcode: 1
2020-10-20 23:04:35,342 INFO    MainThread:10196 [wandb_run.py:_restore():1221] restore
2020-10-20 23:04:35,585 INFO    MainThread:10196 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "2814a8c321ef49f2a53e923ee777198c"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 758
    }
  }
}

2020-10-20 23:04:37,596 INFO    MainThread:10196 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "32eab6e2c25f4e3daa4707643f60ff8e"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 6999
      total_bytes: 6999
    }
  }
}

2020-10-20 23:04:38,739 INFO    MainThread:10196 [wandb_run.py:_show_files():1554] logging synced files
2020-10-20 23:04:38,746 INFO    MainThread:10196 [internal.py:handle_exit():137] Internal process exited
